# Use an official Python runtime as a parent image
FROM 3.10-slim-bullseye

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir poetry && poetry install

# Run app.py when the container launches
CMD ["poetry", "run", "python", "edi_reader", "edi_reader\\conf\\conf_model", "edi_reader\\input"]